[project]
name = "breathing-belt-python"
version = "0.1.0"
description = "Breathing Belt data acquisition and preprocessing"
requires-python = "==3.11.4"

dependencies = [
  "bitalino",
  "keyboard",
  "scipy",
  "matplotlib",
]